### ISSUE TITLE
Encryption: directive should be able to accept more values.

### ISSUE THREAD

**Issue by joker314** [lirantal/express-security-txt#24]
Currently, the _Encryption:_ directive must start with `HTTPS:`. Instead, we should verify it _doesn't_ start with `HTTP:`.

This is branched from a conversation in #23. The RFC discusses examples of two circumstances where a non-web URL can be used:

> Example of a PGP key available from an OPENPGPKEY DNS:
> `Encryption: dns:5d2d37ab76d47d36._openpgpkey.example.com?type=OPENPGPKEY`
>
> Example of a PGP key being referenced by its fingerprint:
> `Encryption: openpgp4fpr:5f2de5521c63a801ab59ccb603d49de44b29100f`

**Comment by joker314** [comment]
ACkk!! I pushed directly to master by accident

**Comment by joker314** [comment]
No and now I've force pushed it away but it's too late :(

**Comment by joker314** [comment]
Hmm, so it doesn't look too bad because the release actually contains the commit, and the commit works. So sorry about this! I wasn't paying attention to which branch I was on.

The problem is, since I've force pushed to `master` the commit won't appear in the history, and I don't believe there's an easy way to fix this.

Sorry again D:

EDIT: again, really sorry. I guess the solution is for you to retrospectively review the commit, and then to disable the bots and place the commit back without triggering them for another release. Sorry again!

**Comment by lirantal** [comment]
No worries, it happens. I think it will be easier for you to work with forks and two repos (origin and upstream) if you aren't already. It will prevent situations like this.

So right now I don't see any change in `master` related to the encryption allowing other than `https` schemas which means this issue is still valid and requires a PR, right?

**Comment by joker314** [comment]
Nope. I was racing against your bot to remove the change, so I force pushed to remove the commit. You can see it https://github.com/lirantal/express-security-txt/commit/cc59e2f04896c163b04e853461b2d171d8875003 but it's just not appearing in the history because of the force pushed removal.

I don't know whether putting it back will cause another release?

And yeah, using forks might be a better idea, or at least using something that warns when trying to push to master.

**Comment by lirantal** [comment]
Yes I've already configured the repo now to set `master` as a protected branch so this doesn't happen again.

To the problem at hand - current situation is that the code-base [doesn't have](https://github.com/lirantal/express-security-txt/blob/master/index.js#L98) the appropriate as mentioned in this issue. Just create a new PR with the fix and we'll land it again.
